package com.michael.qrcode.dao.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.michael.qrcode.dao.model.ScanHistory;

import com.michael.qrcode.dao.model.ScanHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scanHistoryDaoConfig;

    private final ScanHistoryDao scanHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scanHistoryDaoConfig = daoConfigMap.get(ScanHistoryDao.class).clone();
        scanHistoryDaoConfig.initIdentityScope(type);

        scanHistoryDao = new ScanHistoryDao(scanHistoryDaoConfig, this);

        registerDao(ScanHistory.class, scanHistoryDao);
    }
    
    public void clear() {
        scanHistoryDaoConfig.getIdentityScope().clear();
    }

    public ScanHistoryDao getScanHistoryDao() {
        return scanHistoryDao;
    }

}
